// <auto-generated />
namespace MyQuestionnaire.Web.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class RevertRoleToTakeIdenityRole : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RevertRoleToTakeIdenityRole));
        
        string IMigrationMetadata.Id
        {
            get { return "201312190524119_RevertRoleToTakeIdenityRole"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
